In [1]:
from datasets import load_dataset
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

In [2]:
# dataset_name = "squad_v2"
# dataset = load_dataset(dataset_name, split="train")
# eval_dataset = load_dataset(dataset_name, split="validation")
# print("dataset: ",dataset)
# print("eval_dataset: ",eval_dataset)

In [3]:
dataset_path="dataset/small_datset.jsonl"
dataset_name = "tssb_data_3M"
dataset = load_dataset("json", data_files=dataset_path, split="train[:90%]")
eval_dataset = load_dataset("json", data_files=dataset_path, split="train[90%:]")

print("dataset: ",dataset)
print("eval_dataset: ",eval_dataset)

dataset:  Dataset({
    features: ['prompt', 'completion'],
    num_rows: 31500
})
eval_dataset:  Dataset({
    features: ['prompt', 'completion'],
    num_rows: 3500
})

In [4]:
import torch
cuda_available = torch.cuda.is_available()

if cuda_available:
    device_id = 0  # You can change to 1,2,3 if you want other GPUs
    torch.cuda.set_device(device_id)
    # device = torch.device(f"cuda:{device_id}")
    device = torch.device(f"cuda:{device_id}")
    print(f"🖥️ Using GPU {device_id}: {torch.cuda.get_device_name(device_id)}")
else:
    device = torch.device("cpu")
    print("⚙️ No GPU available, using CPU.")

print(f"Device selected: {device}")

🖥️ Using GPU 0: NVIDIA GeForce RTX 4070 SUPER
Device selected: cuda:0

In [5]:
from unsloth import FastLanguageModel
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen3-4B-unsloth-bnb-4bit",
    max_seq_length = 4096,   # Context length - can be longer, but uses more memory
    load_in_4bit = True,     # 4bit uses much less memory
    load_in_8bit = False,    # A bit more accurate, uses 2x memory
    full_finetuning = False, # We have full finetuning now!
    # token = "hf_...",      # use one if using gated models
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!

c:\Users\diego\Documents\Code-Fixer-LLM-Agent\.venv\Lib\site-packages\unsloth_zoo\gradient_checkpointing.py:330: UserWarning: expandable_segments not supported on this platform (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\c10/cuda/CUDAAllocatorConfig.h:28.)
  GPU_BUFFERS = tuple([torch.empty(2*256*2048, dtype = dtype, device = f"cuda:{i}") for i in range(n_gpus)])

==((====))==  Unsloth 2025.4.7: Fast Qwen3 patching. Transformers: 4.51.3.
   \\   /|    NVIDIA GeForce RTX 4070 SUPER. Num GPUs = 1. Max memory: 11.994 GB. Platform: Windows.
O^O/ \_/ \    Torch: 2.7.0+cu126. CUDA: 8.9. CUDA Toolkit: 12.6. Triton: 3.3.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.30. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

In [6]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 64,           # Choose any number > 0! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 64,  # Best to choose alpha = rank or rank*2
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = True,   # We support rank stabilized LoRA
    loftq_config = None,  # And LoftQ
)

Unsloth 2025.4.7 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

In [7]:
import neptune
import neptune.integrations.optuna as optuna_utils

run = neptune.init_run(
    project="TEC1/LLM",
    api_token="eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJiYTI3ZTM1MS1mN2E2LTRjNmUtYTcyMi02MTMyNWU4MWEzMzAifQ==",
)

[neptune] [warning] NeptuneWarning: By default, these monitoring options are disabled in interactive sessions: 'capture_stdout', 'capture_stderr', 'capture_traceback', 'capture_hardware_metrics'. You can set them to 'True' when initializing the run and the monitoring will continue until you call run.stop() or the kernel stops. NOTE: To track the source files, pass their paths to the 'source_code' argument. For help, see: https://docs-legacy.neptune.ai/logging/source_code/

[neptune] [info   ] Neptune initialized. Open in the app: https://app.neptune.ai/TEC1/LLM/e/LLM-2

In [8]:
import evaluate

rouge = evaluate.load("rouge")
bleu = evaluate.load("bleu")
acc = evaluate.load("accuracy")

def preprocess_logits_for_metrics(logits, labels):
    if isinstance(logits, tuple):
        logits = logits[0]
    return logits.argmax(dim=-1)

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    labels = labels[:, 1:]
    preds = preds[:, :-1]

    mask = labels == -100
    labels[mask] = tokenizer.pad_token_id
    preds[mask] = tokenizer.pad_token_id

    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    bleu_score = bleu.compute(predictions=decoded_preds, references=decoded_labels)
    accuracy = acc.compute(predictions=preds[~mask], references=labels[~mask])
    rouge_score = rouge.compute(predictions=decoded_preds, references=decoded_labels)

    return {
        **bleu_score,
        **accuracy,
        **rouge_score
    }

In [9]:
# from trl import SFTTrainer, SFTConfig
# import time
# start=time.time()

# # SFT Config
# config = SFTConfig(
#     dataset_num_proc = 1,
#     #output_dir="./outputs",
#     dataset_text_field="prompt",#Depends on the colum of your data set
#     #dataset_text_field="question",#Depends on the colum of your data set
#     # learning_rate=1e-5,
#     learning_rate=2e-4,
#     per_device_train_batch_size=3,
#     gradient_accumulation_steps=3,
#     num_train_epochs=5,
#     report_to="none",
#     logging_steps=100,
#     max_steps=1000,
#     eval_accumulation_steps=100,
# )
# trainer = SFTTrainer(
#     model=model,  # base or PEFT model
#     tokenizer=tokenizer,
#     train_dataset=dataset,
#     eval_dataset=eval_dataset,
#     args=config,
#     warmup_steps = 5,
#     weight_decay = 0.01,
#     compute_metrics = compute_metrics,
#     preprocess_logits_for_metrics=preprocess_logits_for_metrics,
# )
# metrics = trainer.evaluate()
# print("Metrics:",metrics)
# trainer.train()


# end = time.time()
# length = end - start

# hours = int(length // 3600)
# minutes = int((length % 3600) // 60)
# seconds = int(length % 60)

# print(f"It took {hours} hours, {minutes} minutes, and {seconds} seconds to train the model!")

In [10]:
# metrics = trainer.evaluate()
# print("Metrics:",metrics)

In [11]:
from trl import SFTTrainer, SFTConfig
import time
def objective(trial):
    start=time.time()
    # Suggest hyperparameters
    learning_rate = trial.suggest_float("learning_rate", 1e-5,5e-4, log=True)
    # batch_size = trial.suggest_categorical("per_device_train_batch_size", [4,6,8])
    # gradient_accumulation_steps = trial.suggest_categorical("gradient_accumulation_steps",[4,6,8])
    num_epochs = trial.suggest_int("num_train_epochs", 5, 10)
    batch_size=3

    # SFT Config
    config = SFTConfig(
        dataset_num_proc = 1,
        #output_dir="./outputs",
        dataset_text_field="prompt",#Depends on the colum of your data set
        #dataset_text_field="question",#Depends on the colum of your data set
        # learning_rate=1e-5,
        learning_rate=learning_rate,
        per_device_train_batch_size=3,
        gradient_accumulation_steps=3,
        num_train_epochs=num_epochs,
        report_to="none",
        logging_steps=100,
        max_steps=1000,
        eval_accumulation_steps=100
    )

    trainer = SFTTrainer(
        model=model,  # base or PEFT model
        tokenizer=tokenizer,
        train_dataset=dataset,
        eval_dataset=eval_dataset,
        args=config,
        warmup_steps = 5,
        weight_decay = 0.01,
        compute_metrics = compute_metrics,
        preprocess_logits_for_metrics=preprocess_logits_for_metrics,
    )
    trainer.train()
    metrics = trainer.evaluate()
    print("Metrics:",metrics)

    # Log trial info to Neptunef
    run[f"trial/{trial.number}/metrics"] = metrics
    run[f"trial/{trial.number}/params"] = {
        "learning_rate": learning_rate,
        "num_epochs": num_epochs,
        "eval_bleu":metrics["eval_bleu"],
        "eval_accuracy":metrics["eval_accuracy"],
        "eval_rougeL":metrics["eval_rougeL"],
    }


    end = time.time()
    length = end - start

    hours = int(length // 3600)
    minutes = int((length % 3600) // 60)
    seconds = int(length % 60)

    print(f"It took {hours} hours, {minutes} minutes, and {seconds} seconds to train the model!")

    return metrics["eval_loss"]  # Or any other metric

In [12]:
import optuna
neptune_callback = optuna_utils.NeptuneCallback(run)

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=5, callbacks=[neptune_callback], show_progress_bar=True)

[I 2025-05-13 00:07:28,515] A new study created in memory with name: no-name-982a3e34-972f-48fc-8214-01a53e0046d4

  0%|          | 0/5 [00:00<?, ?it/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 31,500 | Num Epochs = 1 | Total steps = 1,000
O^O/ \_/ \    Batch size per device = 3 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (3 x 3 x 1) = 9
 "-____-"     Trainable parameters = 132,120,576/4,000,000,000 (3.30% trained)

Unsloth: Will smartly offload gradients to save VRAM!

Unsloth: Not an error, but Qwen3ForCausalLM does not accept `num_items_in_batch`.
Using gradient accumulation will be very slightly less accurate.
Read more on gradient accumulation issues here: https://unsloth.ai/blog/gradient

[neptune] [warning] NeptuneUnsupportedType: You're attempting to log a type that is not directly supported by Neptune (<class 'list'>).
        Convert the value to a supported type, such as a string or float, or use stringify_unsupported(obj)
        for dictionaries or collections that contain unsupported values.
        For more, see https://docs-legacy.neptune.ai/help/value_of_unsupported_type

Metrics: {'eval_loss': 2.638505697250366, 'eval_bleu': 0.4608993194311732, 'eval_precisions': [0.7049581028284654, 0.5217755722448763, 0.4446192509654087, 0.38076034856867763], 'eval_brevity_penalty': 0.9226443143068024, 'eval_length_ratio': 0.9254876243878374, 'eval_translation_length': 153829, 'eval_reference_length': 166214, 'eval_accuracy': 0.5874599580914762, 'eval_rouge1': 0.6340991063893164, 'eval_rouge2': 0.4849038814115168, 'eval_rougeL': 0.6318381302252873, 'eval_rougeLsum': 0.6319693521365936, 'eval_runtime': 65.8209, 'eval_samples_per_second': 53.175, 'eval_steps_per_second': 13.294}
It took 0 hours, 16 minutes, and 55 seconds to train the model!
[I 2025-05-13 00:24:24,500] Trial 0 finished with value: 2.638505697250366 and parameters: {'learning_rate': 0.0004917042142406102, 'num_train_epochs': 9}. Best is trial 0 with value: 2.638505697250366.
[W 2025-05-13 00:24:24,642] Param learning_rate unique value length is less than 2.

Unsloth: Tokenizing ["prompt"]:   0%|          | 0/31500 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 31,500 | Num Epochs = 1 | Total steps = 1,000
O^O/ \_/ \    Batch size per device = 3 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (3 x 3 x 1) = 9
 "-____-"     Trainable parameters = 132,120,576/4,000,000,000 (3.30% trained)

Metrics: {'eval_loss': 2.574981212615967, 'eval_bleu': 0.46702060900443476, 'eval_precisions': [0.7091531003266209, 0.5234095453588719, 0.444348692537635, 0.37961967014176184], 'eval_brevity_penalty': 0.9336250187938927, 'eval_length_ratio': 0.9357334520557835, 'eval_translation_length': 155532, 'eval_reference_length': 166214, 'eval_accuracy': 0.5981478359305378, 'eval_rouge1': 0.6353916213657425, 'eval_rouge2': 0.4829526499278254, 'eval_rougeL': 0.6327819354802796, 'eval_rougeLsum': 0.6328817567332985, 'eval_runtime': 66.3793, 'eval_samples_per_second': 52.727, 'eval_steps_per_second': 13.182}
It took 0 hours, 14 minutes, and 17 seconds to train the model!
[I 2025-05-13 00:38:42,764] Trial 1 finished with value: 2.574981212615967 and parameters: {'learning_rate': 6.038857764783957e-05, 'num_train_epochs': 6}. Best is trial 1 with value: 2.574981212615967.

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 31,500 | Num Epochs = 1 | Total steps = 1,000
O^O/ \_/ \    Batch size per device = 3 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (3 x 3 x 1) = 9
 "-____-"     Trainable parameters = 132,120,576/4,000,000,000 (3.30% trained)

Metrics: {'eval_loss': 2.5728213787078857, 'eval_bleu': 0.46821935104826357, 'eval_precisions': [0.7082853118196952, 0.5230940529211423, 0.443149215712562, 0.378500823723229], 'eval_brevity_penalty': 0.937773920095264, 'eval_length_ratio': 0.9396320406223303, 'eval_translation_length': 156180, 'eval_reference_length': 166214, 'eval_accuracy': 0.5993521038560659, 'eval_rouge1': 0.6351252870717952, 'eval_rouge2': 0.48233263678000127, 'eval_rougeL': 0.6324837557538953, 'eval_rougeLsum': 0.6325148382634812, 'eval_runtime': 66.2118, 'eval_samples_per_second': 52.861, 'eval_steps_per_second': 13.215}
It took 0 hours, 14 minutes, and 16 seconds to train the model!
[I 2025-05-13 00:52:59,852] Trial 2 finished with value: 2.5728213787078857 and parameters: {'learning_rate': 1.451159402932002e-05, 'num_train_epochs': 6}. Best is trial 2 with value: 2.5728213787078857.

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 31,500 | Num Epochs = 1 | Total steps = 1,000
O^O/ \_/ \    Batch size per device = 3 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (3 x 3 x 1) = 9
 "-____-"     Trainable parameters = 132,120,576/4,000,000,000 (3.30% trained)

Metrics: {'eval_loss': 2.491055727005005, 'eval_bleu': 0.47350677651258016, 'eval_precisions': [0.7125029342909167, 0.5253213425989008, 0.442965362935619, 0.3770960922790394], 'eval_brevity_penalty': 0.946929884671495, 'eval_length_ratio': 0.9482895544298314, 'eval_translation_length': 157619, 'eval_reference_length': 166214, 'eval_accuracy': 0.6102025578650738, 'eval_rouge1': 0.6418887110321656, 'eval_rouge2': 0.48577614970980215, 'eval_rougeL': 0.6388316951143684, 'eval_rougeLsum': 0.6388868803246801, 'eval_runtime': 65.9167, 'eval_samples_per_second': 53.097, 'eval_steps_per_second': 13.274}
It took 0 hours, 14 minutes, and 15 seconds to train the model!
[I 2025-05-13 01:07:15,521] Trial 3 finished with value: 2.491055727005005 and parameters: {'learning_rate': 0.00016632987291245448, 'num_train_epochs': 10}. Best is trial 3 with value: 2.491055727005005.

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 31,500 | Num Epochs = 1 | Total steps = 1,000
O^O/ \_/ \    Batch size per device = 3 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (3 x 3 x 1) = 9
 "-____-"     Trainable parameters = 132,120,576/4,000,000,000 (3.30% trained)

Metrics: {'eval_loss': 2.499626874923706, 'eval_bleu': 0.4747823730949435, 'eval_precisions': [0.7112129448201757, 0.5251373537586452, 0.44237814959328087, 0.3765283325434974], 'eval_brevity_penalty': 0.9506674266800653, 'eval_length_ratio': 0.9518452115946912, 'eval_translation_length': 158210, 'eval_reference_length': 166214, 'eval_accuracy': 0.611153929526241, 'eval_rouge1': 0.6400516778125096, 'eval_rouge2': 0.4838538665861545, 'eval_rougeL': 0.6367062043518638, 'eval_rougeLsum': 0.6369209256537016, 'eval_runtime': 65.7882, 'eval_samples_per_second': 53.201, 'eval_steps_per_second': 13.3}
It took 0 hours, 14 minutes, and 16 seconds to train the model!
[I 2025-05-13 01:21:31,794] Trial 4 finished with value: 2.499626874923706 and parameters: {'learning_rate': 1.5519288867325017e-05, 'num_train_epochs': 9}. Best is trial 3 with value: 2.491055727005005.

In [13]:
# Get the best parameters
best_trial = study.best_trial

best_params = best_trial.params
print("best_params: ",best_params)

best_value = best_trial.value
print("Eval loss:", best_value)
run.stop()

best_params:  {'learning_rate': 0.00016632987291245448, 'num_train_epochs': 10}
Eval loss: 2.491055727005005
[neptune] [info   ] Shutting down background jobs, please wait a moment...
[neptune] [info   ] Done!
[neptune] [info   ] Waiting for the remaining 54 operations to synchronize with Neptune. Do not kill this process.
[neptune] [info   ] All 54 operations synced, thanks for waiting!
[neptune] [info   ] Explore the metadata in the Neptune app: https://app.neptune.ai/TEC1/LLM/e/LLM-2/metadata

: